### ISSUE TITLE
Allow meta-data support for updating location ie. updateCurrentLocation method

### ISSUE THREAD

**Issue by ravikanth-tummala** [roam-ai/roam-android#11]
### Discussed in https://github.com/roam-ai/roam-android/discussions/10

<div type='discussions-op-text'>

<sup>Originally posted by **ravikanth-tummala** July 26, 2021</sup>
**When**
being a developer, during `updateCurrentLocation()` method
**I want to**
send custom meta-data (ie. key value pairs) along with that specific location update
**So that**
we can tag the meta-data only to single location update and not for all the location update, when we add the same using `publishSave()` method.

**Things to notice**
- If the `publishSave()` method already has meta-data added, this will be overwritten by the meta-data passed in `updateCurrentLocation()` method and applied only for that specific location update and rest will continue to use the previous configurations passed in `publishSave()` method.
- The meta-data information should be available below for user location subsciptions.
```swift
func didUpdateLocation(_ location: RoamLocation) {
        //Receive user location along with meta-data
    }
func didReceiveUserLocation(_ location: RoamLocationReceived) {
         //Receive other users' location along with meta-data
    }
```</div>

**Comment by jothipriyadharshanr** [comment]
Resolved
